"""
Generate 10,000 unique license keys per product.

Outputs (per product):
  keys/{ProductName}_keys.txt    — plaintext keys for distribution
  keys/{ProductName}_hashes.txt  — SHA-256 hashes bundled into the EXE

Key format:  XXXX-XXXX-XXXX-XXXX  (uppercase, no ambiguous chars O/0/I/1/l)
Security:    EXE stores SHA256(product_id + ":" + key) — not the raw keys.
             Keys from one product cannot activate another product.
"""
import hashlib
import secrets
import string
from pathlib import Path

# Unambiguous characters only (no 0/O, 1/I/l)
CHARS = "ABCDEFGHJKMNPQRSTUVWXYZ23456789"
N_KEYS = 10_000

PRODUCTS = [
    {"appdata": "LeadScraperPro", "dir": "scraper_node"},
    {"appdata": "Discovery1",     "dir": "discovery1"},
    {"appdata": "AtomicScraper",  "dir": "atomicscraper"},
    {"appdata": "ProspectHunter", "dir": "prospecthunter"},
    {"appdata": "LeadsBaby",      "dir": "leadsbaby"},
    {"appdata": "LeadRipper",     "dir": "leadripper"},
]

ROOT = Path(__file__).parent
KEYS_DIR = ROOT / "keys"
KEYS_DIR.mkdir(exist_ok=True)


def make_key() -> str:
    def seg():
        return "".join(secrets.choice(CHARS) for _ in range(4))
    return f"{seg()}-{seg()}-{seg()}-{seg()}"


def hash_key(product_id: str, key: str) -> str:
    return hashlib.sha256(f"{product_id}:{key}".encode()).hexdigest()


for p in PRODUCTS:
    pid     = p["appdata"]
    prod_dir = ROOT / p["dir"]

    keys: list[str] = []
    seen: set[str]  = set()
    while len(keys) < N_KEYS:
        k = make_key()
        if k not in seen:
            seen.add(k)
            keys.append(k)

    hashes = [hash_key(pid, k) for k in keys]

    # Plaintext keys for distribution
    (KEYS_DIR / f"{pid}_keys.txt").write_text("\n".join(keys), encoding="utf-8")

    # Embed hashes as a Python module (compiled to bytecode inside EXE — no separate file)
    lines = ["# Auto-generated by generate_keys.py — do not edit\n",
             "VALID_HASHES = frozenset({\n"]
    for h in hashes:
        lines.append(f'    "{h}",\n')
    lines.append("})\n")
    (prod_dir / "license_hashes.py").write_text("".join(lines), encoding="utf-8")

    print(f"  {pid}: {N_KEYS:,} keys written")

print("\nDone. Distribute the keys/ *_keys.txt files to customers.")
print("Hashes are embedded as compiled bytecode inside each EXE.")
