"""
All Industries / Google Maps Search Terms
~500+ distinct search queries organized by category.
Terms are written as someone would type them into Google Maps.
"""

ALL_INDUSTRIES = {
    "Food & Restaurants": [
        "restaurants near me",
        "pizza restaurants",
        "burger restaurants",
        "fast food restaurants",
        "mexican restaurants",
        "chinese restaurants",
        "italian restaurants",
        "sushi restaurants",
        "thai restaurants",
        "indian restaurants",
        "vietnamese restaurants",
        "korean restaurants",
        "japanese restaurants",
        "mediterranean restaurants",
        "greek restaurants",
        "american restaurants",
        "seafood restaurants",
        "steakhouses",
        "BBQ restaurants",
        "sandwich shops",
        "sub shops",
        "deli restaurants",
        "breakfast restaurants",
        "brunch restaurants",
        "diners",
        "cafes",
        "coffee shops",
        "bakeries",
        "donut shops",
        "ice cream shops",
        "dessert shops",
        "food trucks",
        "catering companies",
        "buffet restaurants",
        "vegan restaurants",
        "vegetarian restaurants",
        "gluten-free restaurants",
        "halal restaurants",
        "kosher restaurants",
        "wings restaurants",
        "taco shops",
        "ramen restaurants",
        "pho restaurants",
        "noodle restaurants",
        "soup restaurants",
        "salad bars",
        "juice bars",
        "smoothie shops",
        "boba tea shops",
        "wine bars",
        "tapas bars",
        "gastropubs",
        "farm-to-table restaurants",
    ],

    "Home Services": [
        "plumbers near me",
        "plumbing companies",
        "HVAC companies",
        "air conditioning repair",
        "heating repair",
        "furnace repair",
        "electricians near me",
        "electrical contractors",
        "roofers near me",
        "roofing companies",
        "roof repair",
        "roof replacement",
        "general contractors",
        "home remodeling contractors",
        "kitchen remodelers",
        "bathroom remodelers",
        "handyman services",
        "home repair services",
        "drywall contractors",
        "painting contractors",
        "interior painters",
        "exterior painters",
        "flooring companies",
        "hardwood floor installation",
        "tile installers",
        "carpet installers",
        "window installers",
        "door installers",
        "garage door repair",
        "garage door installation",
        "insulation contractors",
        "waterproofing services",
        "foundation repair",
        "siding contractors",
        "deck builders",
        "fence companies",
        "gutter cleaning",
        "gutter installation",
        "chimney sweep",
        "chimney repair",
        "pool repair",
        "pool cleaning services",
        "septic tank services",
        "drain cleaning",
        "water heater repair",
        "water heater installation",
        "solar panel installation",
        "generator installation",
        "locksmith services",
        "home security installation",
        "smart home installation",
        "appliance repair",
    ],

    "Health & Medical": [
        "doctors near me",
        "primary care physicians",
        "family doctors",
        "urgent care clinics",
        "walk-in clinics",
        "dentists near me",
        "dental clinics",
        "orthodontists",
        "oral surgeons",
        "periodontists",
        "endodontists",
        "pediatric dentists",
        "chiropractors near me",
        "physical therapists",
        "occupational therapists",
        "speech therapists",
        "massage therapists",
        "acupuncturists",
        "optometrists",
        "eye doctors",
        "ophthalmologists",
        "dermatologists",
        "skin care clinics",
        "pediatricians",
        "gynecologists",
        "OB-GYN doctors",
        "cardiologists",
        "neurologists",
        "orthopedic surgeons",
        "plastic surgeons",
        "cosmetic surgeons",
        "psychiatrists",
        "psychologists",
        "therapists near me",
        "counselors near me",
        "mental health clinics",
        "addiction treatment centers",
        "rehabilitation centers",
        "nursing homes",
        "assisted living facilities",
        "home health care",
        "hospice care",
        "fertility clinics",
        "allergy doctors",
        "gastroenterologists",
        "radiologists",
        "medical imaging centers",
        "labs near me",
        "blood testing labs",
        "pharmacies near me",
        "compounding pharmacies",
        "naturopathic doctors",
        "holistic health centers",
        "weight loss clinics",
        "medical spas",
    ],

    "Legal Services": [
        "lawyers near me",
        "attorneys near me",
        "law firms near me",
        "personal injury lawyers",
        "car accident lawyers",
        "workers compensation attorneys",
        "medical malpractice lawyers",
        "criminal defense attorneys",
        "DUI lawyers",
        "divorce lawyers",
        "family law attorneys",
        "child custody lawyers",
        "estate planning attorneys",
        "probate lawyers",
        "bankruptcy attorneys",
        "immigration lawyers",
        "business lawyers",
        "corporate attorneys",
        "employment lawyers",
        "wrongful termination attorneys",
        "discrimination lawyers",
        "real estate attorneys",
        "intellectual property lawyers",
        "patent attorneys",
        "trademark lawyers",
        "contract lawyers",
        "social security disability lawyers",
        "nursing home abuse lawyers",
        "product liability lawyers",
        "tax attorneys",
        "traffic ticket lawyers",
        "expungement lawyers",
        "civil rights attorneys",
    ],

    "Financial Services": [
        "accountants near me",
        "CPA firms",
        "tax preparation services",
        "bookkeeping services",
        "financial advisors",
        "financial planners",
        "investment advisors",
        "wealth management firms",
        "banks near me",
        "credit unions near me",
        "mortgage brokers",
        "mortgage lenders",
        "home loan companies",
        "insurance agencies",
        "auto insurance agents",
        "home insurance agents",
        "life insurance agents",
        "health insurance brokers",
        "business insurance agents",
        "payroll services",
        "business consulting firms",
        "tax consulting firms",
        "credit repair services",
        "debt consolidation services",
        "pawn shops",
        "check cashing services",
        "payday loan companies",
        "ATMs near me",
        "currency exchange",
        "stock brokers",
        "retirement planning services",
        "estate planning financial advisors",
    ],

    "Beauty & Personal Care": [
        "hair salons near me",
        "beauty salons",
        "hair stylists",
        "barber shops",
        "men's haircuts",
        "women's salons",
        "nail salons",
        "nail spas",
        "gel nail salons",
        "acrylic nail salons",
        "eyelash extensions",
        "eyebrow threading",
        "eyebrow microblading",
        "permanent makeup",
        "tattoo parlors",
        "tattoo removal",
        "piercing studios",
        "spas near me",
        "day spas",
        "massage spas",
        "waxing salons",
        "laser hair removal",
        "skin care clinics",
        "facials near me",
        "chemical peels",
        "botox injections",
        "dermal fillers",
        "lip fillers",
        "tanning salons",
        "spray tan services",
        "hair coloring salons",
        "hair extensions",
        "keratin treatment salons",
        "lice treatment centers",
        "makeup artists",
        "bridal makeup",
    ],

    "Auto Services": [
        "auto repair shops",
        "car mechanics near me",
        "oil change services",
        "tire shops",
        "tire installation",
        "wheel alignment services",
        "brake repair shops",
        "transmission repair",
        "engine repair",
        "auto body shops",
        "collision repair",
        "dent repair",
        "windshield repair",
        "windshield replacement",
        "auto glass repair",
        "car detailing services",
        "car wash near me",
        "auto dealerships",
        "used car dealerships",
        "car lots",
        "car rental",
        "auto parts stores",
        "junkyard near me",
        "salvage yards",
        "towing services",
        "roadside assistance",
        "smog check stations",
        "car inspection services",
        "vehicle registration services",
        "motorcycle repair shops",
        "RV repair shops",
        "truck repair shops",
        "diesel mechanics",
        "trailer repair",
        "auto electrical repair",
        "AC repair for cars",
        "exhaust repair",
        "muffler shops",
        "radiator repair",
        "car audio installation",
        "window tinting",
        "paint protection film",
    ],

    "Real Estate": [
        "real estate agents near me",
        "realtors near me",
        "real estate brokers",
        "property management companies",
        "rental property management",
        "commercial real estate agents",
        "residential real estate agents",
        "luxury real estate agents",
        "first-time homebuyer agents",
        "home buyers agents",
        "property appraisers",
        "home appraisers",
        "real estate attorneys",
        "title companies",
        "escrow companies",
        "home inspectors",
        "building inspectors",
        "HOA management companies",
        "apartment complexes",
        "apartment rentals",
        "rental agencies",
        "storage units",
        "self-storage facilities",
    ],

    "Fitness & Sports": [
        "gyms near me",
        "fitness centers",
        "personal trainers",
        "yoga studios",
        "pilates studios",
        "crossfit gyms",
        "boxing gyms",
        "MMA gyms",
        "martial arts schools",
        "karate schools",
        "judo schools",
        "taekwondo schools",
        "Brazilian jiu-jitsu gyms",
        "kickboxing gyms",
        "cycling studios",
        "spin studios",
        "barre studios",
        "dance studios",
        "ballet studios",
        "swimming pools",
        "aquatic centers",
        "golf courses",
        "driving ranges",
        "tennis courts",
        "racquetball courts",
        "basketball courts",
        "rock climbing gyms",
        "trampoline parks",
        "sports complexes",
        "ice skating rinks",
        "roller skating rinks",
        "bowling alleys",
        "batting cages",
        "shooting ranges",
        "archery ranges",
        "sports nutrition stores",
        "supplement stores",
    ],

    "Education": [
        "tutoring centers",
        "private tutors",
        "math tutors",
        "reading tutors",
        "SAT prep courses",
        "ACT prep classes",
        "test prep centers",
        "daycares near me",
        "childcare centers",
        "preschools",
        "private schools",
        "charter schools",
        "montessori schools",
        "elementary schools",
        "middle schools",
        "high schools",
        "trade schools",
        "vocational schools",
        "community colleges",
        "universities",
        "colleges near me",
        "driving schools",
        "music schools",
        "piano lessons",
        "guitar lessons",
        "violin lessons",
        "voice lessons",
        "art classes",
        "coding bootcamps",
        "language schools",
        "ESL classes",
        "Spanish classes",
        "dance lessons",
        "cooking classes",
        "after-school programs",
        "summer camps",
        "college counseling",
        "special education services",
        "learning centers",
    ],

    "Retail": [
        "clothing stores",
        "boutique clothing stores",
        "thrift stores",
        "consignment shops",
        "shoe stores",
        "sporting goods stores",
        "outdoor gear stores",
        "electronics stores",
        "computer stores",
        "phone repair shops",
        "cell phone stores",
        "hardware stores",
        "home improvement stores",
        "furniture stores",
        "mattress stores",
        "appliance stores",
        "grocery stores",
        "supermarkets",
        "specialty food stores",
        "liquor stores",
        "wine shops",
        "book stores",
        "toy stores",
        "baby stores",
        "children's clothing stores",
        "gift shops",
        "flower shops",
        "florists",
        "jewelry stores",
        "watch stores",
        "optical stores",
        "eyeglass stores",
        "art supply stores",
        "craft stores",
        "hobby shops",
        "bike shops",
        "music stores",
        "gun shops",
        "vape shops",
        "smoke shops",
        "dispensaries",
        "dollar stores",
        "discount stores",
        "convenience stores",
        "pharmacy",
        "drugstores",
    ],

    "Professional Services": [
        "marketing agencies",
        "digital marketing agencies",
        "SEO companies",
        "social media marketing agencies",
        "advertising agencies",
        "web design companies",
        "web development companies",
        "graphic design studios",
        "branding agencies",
        "PR firms",
        "public relations companies",
        "IT support companies",
        "IT consulting firms",
        "managed IT services",
        "cybersecurity companies",
        "software development companies",
        "app development companies",
        "data analytics firms",
        "business consulting firms",
        "management consulting",
        "HR consulting firms",
        "staffing agencies",
        "temp agencies",
        "recruiting firms",
        "headhunters",
        "translation services",
        "document translation",
        "printing companies",
        "sign companies",
        "sign makers",
        "promotional products companies",
        "courier services",
        "mail services",
        "shipping companies",
        "notary services",
        "process servers",
        "private investigators",
        "security companies",
        "janitorial supply companies",
        "office supply stores",
    ],

    "Pet Services": [
        "veterinarians near me",
        "vet clinics",
        "animal hospitals",
        "emergency vet clinics",
        "pet groomers",
        "dog groomers",
        "cat groomers",
        "pet boarding",
        "dog boarding",
        "dog daycare",
        "pet sitters",
        "dog walkers",
        "pet stores",
        "pet supply stores",
        "pet adoption centers",
        "animal shelters",
        "dog trainers",
        "dog obedience schools",
        "pet rehabilitation",
        "holistic vets",
        "exotic animal vets",
        "aquarium stores",
        "bird stores",
        "reptile stores",
        "pet cremation services",
        "pet cemeteries",
    ],

    "Entertainment & Nightlife": [
        "bars near me",
        "sports bars",
        "cocktail bars",
        "dive bars",
        "nightclubs",
        "dance clubs",
        "live music venues",
        "concert halls",
        "comedy clubs",
        "karaoke bars",
        "movie theaters",
        "drive-in theaters",
        "escape rooms",
        "arcades",
        "amusement parks",
        "theme parks",
        "miniature golf",
        "go-kart tracks",
        "paintball arenas",
        "laser tag",
        "bowling alleys",
        "pool halls",
        "billiards",
        "casinos",
        "poker rooms",
        "bingo halls",
        "theaters",
        "playhouses",
        "art galleries",
        "museums",
        "science centers",
        "aquariums",
        "zoos",
        "botanical gardens",
        "event venues",
        "banquet halls",
        "wedding venues",
        "party venues",
        "axe throwing",
        "virtual reality arcades",
    ],

    "Construction": [
        "general contractors near me",
        "construction companies",
        "home builders",
        "custom home builders",
        "commercial construction companies",
        "landscaping companies",
        "lawn care services",
        "tree service companies",
        "tree removal",
        "tree trimming",
        "stump grinding",
        "irrigation companies",
        "sprinkler installation",
        "hardscaping companies",
        "patio builders",
        "concrete contractors",
        "asphalt contractors",
        "driveway paving",
        "paving companies",
        "masonry contractors",
        "brick masons",
        "stone contractors",
        "excavation companies",
        "grading contractors",
        "land clearing services",
        "demolition companies",
        "swimming pool builders",
        "pond builders",
        "retaining wall contractors",
        "drainage contractors",
        "steel building companies",
        "metal building contractors",
        "cabinet makers",
        "custom cabinets",
        "millwork companies",
        "trim carpenters",
    ],

    "Travel & Hospitality": [
        "hotels near me",
        "motels near me",
        "bed and breakfasts",
        "boutique hotels",
        "luxury hotels",
        "budget hotels",
        "extended stay hotels",
        "resorts near me",
        "vacation rentals",
        "short-term rentals",
        "hostels",
        "campgrounds",
        "RV parks",
        "glamping sites",
        "travel agencies",
        "tour operators",
        "airport shuttle services",
        "limousine services",
        "taxi services",
        "ride share services",
        "car rental agencies",
        "RV rentals",
        "boat rentals",
        "charter boats",
        "fishing charters",
        "whale watching tours",
        "wine tours",
        "brewery tours",
        "food tours",
        "ghost tours",
        "bus tours",
        "helicopter tours",
        "hot air balloon rides",
        "travel insurance companies",
        "cruise agencies",
    ],

    "Religious Organizations": [
        "churches near me",
        "catholic churches",
        "protestant churches",
        "baptist churches",
        "methodist churches",
        "presbyterian churches",
        "lutheran churches",
        "episcopal churches",
        "non-denominational churches",
        "evangelical churches",
        "pentecostal churches",
        "orthodox churches",
        "synagogues near me",
        "jewish temples",
        "mosques near me",
        "islamic centers",
        "hindu temples",
        "buddhist temples",
        "sikh temples",
        "jehovah's witnesses kingdom hall",
        "seventh-day adventist churches",
        "LDS churches",
        "mormon churches",
        "religious bookstores",
        "christian schools",
        "religious retreat centers",
    ],

    "Government & Non-Profit": [
        "city hall near me",
        "county courthouse",
        "DMV near me",
        "social security offices",
        "post offices near me",
        "public libraries near me",
        "fire stations",
        "police stations",
        "public health departments",
        "food banks near me",
        "homeless shelters",
        "domestic violence shelters",
        "community centers",
        "senior centers",
        "youth centers",
        "non-profit organizations",
        "charities near me",
        "Goodwill stores",
        "Salvation Army stores",
        "Habitat for Humanity",
        "Red Cross chapters",
        "Veterans Affairs offices",
        "job centers",
        "workforce development centers",
        "unemployment offices",
    ],

    "Cleaning Services": [
        "house cleaning services",
        "maid services",
        "residential cleaning companies",
        "commercial cleaning companies",
        "office cleaning services",
        "janitorial services",
        "carpet cleaning services",
        "upholstery cleaning",
        "window cleaning services",
        "pressure washing services",
        "power washing services",
        "duct cleaning services",
        "dryer vent cleaning",
        "biohazard cleaning",
        "crime scene cleaning",
        "flood damage cleanup",
        "fire damage cleanup",
        "mold remediation",
        "water damage restoration",
        "disaster restoration services",
        "move-in cleaning",
        "move-out cleaning",
        "post-construction cleaning",
        "deep cleaning services",
        "laundry services",
        "dry cleaning",
        "laundromats",
    ],

    "Moving & Storage": [
        "moving companies near me",
        "local movers",
        "long distance movers",
        "residential moving companies",
        "commercial moving companies",
        "office movers",
        "piano movers",
        "furniture movers",
        "packing services",
        "moving truck rentals",
        "portable storage containers",
        "storage units near me",
        "self-storage facilities",
        "climate-controlled storage",
        "vehicle storage",
        "boat storage",
        "RV storage",
        "junk removal services",
        "hauling services",
        "estate cleanout services",
        "furniture donation pickup",
    ],

    "Pest Control": [
        "pest control companies",
        "exterminator near me",
        "bed bug treatment",
        "termite treatment",
        "termite inspection",
        "ant control",
        "cockroach exterminator",
        "mosquito control",
        "flea exterminator",
        "wasp removal",
        "bee removal",
        "rodent control",
        "rat exterminator",
        "mouse control",
        "wildlife removal",
        "squirrel removal",
        "raccoon removal",
        "bird control",
        "spider exterminator",
        "tick control",
        "fumigation services",
        "organic pest control",
    ],

    "Photography & Media": [
        "photographers near me",
        "wedding photographers",
        "portrait photographers",
        "family photographers",
        "newborn photographers",
        "maternity photographers",
        "real estate photographers",
        "commercial photographers",
        "event photographers",
        "headshot photographers",
        "videographers near me",
        "wedding videographers",
        "video production companies",
        "drone photography",
        "aerial photography",
        "photo studios",
        "photo editing services",
        "photo printing services",
        "photo booths",
        "graphic designers",
        "logo designers",
        "illustrators",
        "animation studios",
        "podcast studios",
        "recording studios",
        "music producers",
        "voice over artists",
        "YouTube video editors",
        "social media content creators",
        "marketing photographers",
    ],

    "Childcare & Family": [
        "babysitters near me",
        "nanny agencies",
        "au pair agencies",
        "childcare near me",
        "after school care",
        "before school care",
        "summer camps for kids",
        "sports camps",
        "STEM camps",
        "art camps",
        "music camps",
        "cheerleading gyms",
        "gymnastics classes",
        "swimming lessons",
        "kids birthday party venues",
        "kids party planning",
        "children's party entertainers",
        "face painters",
        "balloon artists",
        "magicians",
        "clowns for hire",
        "bounce house rentals",
        "family counseling",
        "pediatric therapy",
        "child psychologists",
    ],

    "Weddings & Events": [
        "wedding planners",
        "event planners",
        "wedding venues",
        "wedding caterers",
        "wedding florists",
        "wedding cake bakeries",
        "wedding photographers",
        "wedding videographers",
        "wedding DJs",
        "wedding bands",
        "wedding dress shops",
        "bridal boutiques",
        "tuxedo rentals",
        "wedding limo services",
        "wedding transportation",
        "event rental companies",
        "tent rental companies",
        "chair and table rentals",
        "wedding invitations",
        "wedding makeup artists",
        "wedding hair stylists",
        "rehearsal dinner venues",
        "party supply stores",
        "balloon decorators",
        "event lighting companies",
    ],

    "Funeral & Memorial": [
        "funeral homes near me",
        "funeral directors",
        "cremation services",
        "burial services",
        "cemeteries near me",
        "mausoleums",
        "grief counseling",
        "estate services",
        "memorial services",
        "headstone makers",
        "monument companies",
        "obituary services",
        "death doulas",
    ],

    "Automotive Specialty": [
        "car wrapping services",
        "vinyl wrap shops",
        "auto upholstery shops",
        "rim shops",
        "wheel customization",
        "performance auto shops",
        "car lift installation",
        "truck accessories shops",
        "jeep accessories",
        "off-road vehicle shops",
        "diesel performance shops",
        "turbo installation",
        "supercharger installation",
        "lowrider shops",
        "classic car restoration",
        "antique auto restoration",
        "boat repair shops",
        "marine mechanics",
        "motorcycle dealerships",
        "ATV dealerships",
        "golf cart dealers",
        "electric vehicle charging stations",
        "EV repair shops",
    ],
}


def get_all_queries() -> list[str]:
    """Returns a flat list of all search queries across all categories."""
    queries = []
    for terms in ALL_INDUSTRIES.values():
        queries.extend(terms)
    return queries


def get_queries_by_category(category: str) -> list[str]:
    """
    Returns list of search queries for a given category name.
    Case-insensitive match. Returns empty list if category not found.
    """
    for cat_name, terms in ALL_INDUSTRIES.items():
        if cat_name.lower() == category.lower():
            return list(terms)
    return []


def search_industries(query: str) -> dict:
    """
    Returns a dict of category -> [matching queries] for UI search.
    Matches query against both category names and individual search terms.
    Case-insensitive.
    """
    q = query.lower().strip()
    if not q:
        return {}

    results = {}
    for category, terms in ALL_INDUSTRIES.items():
        matched = []
        # Check if query matches category name
        if q in category.lower():
            matched = list(terms)
        else:
            # Check individual terms
            matched = [t for t in terms if q in t.lower()]

        if matched:
            results[category] = matched

    return results


def list_categories() -> list[str]:
    """Returns a sorted list of all category names."""
    return sorted(ALL_INDUSTRIES.keys())


if __name__ == "__main__":
    all_q = get_all_queries()
    print(f"Total search queries: {len(all_q)}")
    print(f"Total categories: {len(ALL_INDUSTRIES)}")
    print()
    for cat, terms in ALL_INDUSTRIES.items():
        print(f"  {cat}: {len(terms)} terms")
