"""
US cities ranked by population. Used for city-tier scraping.
"""

# Top 1000 US cities by population (city, state)
US_CITIES = [
    ("New York", "NY"), ("Los Angeles", "CA"), ("Chicago", "IL"), ("Houston", "TX"),
    ("Phoenix", "AZ"), ("Philadelphia", "PA"), ("San Antonio", "TX"), ("San Diego", "CA"),
    ("Dallas", "TX"), ("San Jose", "CA"), ("Austin", "TX"), ("Jacksonville", "FL"),
    ("Fort Worth", "TX"), ("Columbus", "OH"), ("Charlotte", "NC"), ("San Francisco", "CA"),
    ("Indianapolis", "IN"), ("Seattle", "WA"), ("Denver", "CO"), ("Nashville", "TN"),
    ("Oklahoma City", "OK"), ("El Paso", "TX"), ("Washington", "DC"), ("Louisville", "KY"),
    ("Las Vegas", "NV"), ("Memphis", "TN"), ("Portland", "OR"), ("Baltimore", "MD"),
    ("Milwaukee", "WI"), ("Albuquerque", "NM"), ("Tucson", "AZ"), ("Fresno", "CA"),
    ("Sacramento", "CA"), ("Mesa", "AZ"), ("Kansas City", "MO"), ("Atlanta", "GA"),
    ("Omaha", "NE"), ("Colorado Springs", "CO"), ("Raleigh", "NC"), ("Long Beach", "CA"),
    ("Virginia Beach", "VA"), ("Miami", "FL"), ("Oakland", "CA"), ("Minneapolis", "MN"),
    ("Tampa", "FL"), ("Tulsa", "OK"), ("Arlington", "TX"), ("New Orleans", "LA"),
    ("Wichita", "KS"), ("Cleveland", "OH"), ("Bakersfield", "CA"), ("Aurora", "CO"),
    ("Anaheim", "CA"), ("Santa Ana", "CA"), ("Corpus Christi", "TX"), ("Riverside", "CA"),
    ("Lexington", "KY"), ("St. Louis", "MO"), ("Pittsburgh", "PA"), ("Stockton", "CA"),
    ("Anchorage", "AK"), ("Cincinnati", "OH"), ("St. Paul", "MN"), ("Greensboro", "NC"),
    ("Toledo", "OH"), ("Newark", "NJ"), ("Plano", "TX"), ("Henderson", "NV"),
    ("Lincoln", "NE"), ("Buffalo", "NY"), ("Fort Wayne", "IN"), ("Jersey City", "NJ"),
    ("Chula Vista", "CA"), ("Orlando", "FL"), ("St. Petersburg", "FL"), ("Laredo", "TX"),
    ("Norfolk", "VA"), ("Madison", "WI"), ("Durham", "NC"), ("Lubbock", "TX"),
    ("Winston-Salem", "NC"), ("Garland", "TX"), ("Glendale", "AZ"), ("Hialeah", "FL"),
    ("Reno", "NV"), ("Baton Rouge", "LA"), ("Irvine", "CA"), ("Chesapeake", "VA"),
    ("Irving", "TX"), ("Scottsdale", "AZ"), ("North Las Vegas", "NV"), ("Fremont", "CA"),
    ("Gilbert", "AZ"), ("San Bernardino", "CA"), ("Birmingham", "AL"), ("Boise", "ID"),
    ("Rochester", "NY"), ("Richmond", "VA"), ("Spokane", "WA"), ("Des Moines", "IA"),
    ("Montgomery", "AL"), ("Modesto", "CA"), ("Fayetteville", "NC"), ("Tacoma", "WA"),
    ("Akron", "OH"), ("Aurora", "IL"), ("Yonkers", "NY"), ("Little Rock", "AR"),
    ("Columbus", "GA"), ("Glendale", "CA"), ("Grand Rapids", "MI"), ("Shreveport", "LA"),
    ("Huntington Beach", "CA"), ("Salt Lake City", "UT"), ("Tallahassee", "FL"),
    ("Huntsville", "AL"), ("Worcester", "MA"), ("Knoxville", "TN"), ("Providence", "RI"),
    ("Mobile", "AL"), ("Tempe", "AZ"), ("Brownsville", "TX"), ("Fort Lauderdale", "FL"),
    ("Newport News", "VA"), ("Chattanooga", "TN"), ("Santa Clarita", "CA"),
    ("Garden Grove", "CA"), ("Oceanside", "CA"), ("Moreno Valley", "CA"), ("Fontana", "CA"),
    ("Rancho Cucamonga", "CA"), ("Oxnard", "CA"), ("Pomona", "CA"), ("Frisco", "TX"),
    ("Killeen", "TX"), ("Clarksville", "TN"), ("Lakewood", "CO"), ("Hollywood", "FL"),
    ("Springfield", "MO"), ("Salinas", "CA"), ("Sunnyvale", "CA"), ("Eugene", "OR"),
    ("Roseville", "CA"), ("Ontario", "CA"), ("Hampton", "VA"), ("Hayward", "CA"),
    ("Pomona", "CA"), ("Escondido", "CA"), ("Torrance", "CA"), ("Paterson", "NJ"),
    ("Alexandria", "VA"), ("Savannah", "GA"), ("Rockford", "IL"), ("Surprise", "AZ"),
    ("Bridgeport", "CT"), ("Mesquite", "TX"), ("Lakewood", "CA"), ("Macon", "GA"),
    ("Kansas City", "KS"), ("Dayton", "OH"), ("Syracuse", "NY"), ("Hollywood", "FL"),
    ("Pasadena", "TX"), ("Orange", "CA"), ("Fullerton", "CA"), ("McAllen", "TX"),
    ("Sioux Falls", "SD"), ("Cedar Rapids", "IA"), ("Cary", "NC"), ("Concord", "CA"),
    ("Visalia", "CA"), ("Thousand Oaks", "CA"), ("Simi Valley", "CA"), ("Roseville", "CA"),
    ("Elizabeth", "NJ"), ("Gainesville", "FL"), ("Sterling Heights", "MI"), ("Carrollton", "TX"),
    ("Coral Springs", "FL"), ("Columbia", "SC"), ("Stamford", "CT"), ("Midland", "TX"),
    ("Bellevue", "WA"), ("Murfreesboro", "TN"), ("Palmdale", "CA"), ("Beaumont", "TX"),
    ("Columbia", "MO"), ("Miramar", "FL"), ("West Valley City", "UT"), ("Sunnyvale", "CA"),
    ("Cape Coral", "FL"), ("Peoria", "IL"), ("Springfield", "IL"), ("Fayetteville", "AR"),
    ("Hayward", "CA"), ("Lancaster", "CA"), ("Salinas", "CA"), ("Pomona", "CA"),
    ("Torrance", "CA"), ("Lakewood", "CO"), ("Pasadena", "CA"), ("Pomona", "CA"),
    ("Tallahassee", "FL"), ("Pembroke Pines", "FL"), ("Waco", "TX"), ("Overland Park", "KS"),
    ("Vancouver", "WA"), ("Peoria", "AZ"), ("Amarillo", "TX"), ("Gainesville", "FL"),
    ("Athens", "GA"), ("Chattanooga", "TN"), ("Springfield", "MA"), ("Fort Collins", "CO"),
    ("Corona", "CA"), ("Elk Grove", "CA"), ("Salem", "OR"), ("McKinney", "TX"),
    ("Warren", "MI"), ("Tempe", "AZ"), ("Naperville", "IL"), ("Rockford", "IL"),
    ("Joliet", "IL"), ("Paterson", "NJ"), ("Savannah", "GA"), ("Bridgeport", "CT"),
    ("Baton Rouge", "LA"), ("Shreveport", "LA"), ("Lubbock", "TX"), ("Reno", "NV"),
    ("Hialeah", "FL"), ("Laredo", "TX"), ("Garland", "TX"), ("Irving", "TX"),
    ("Chesapeake", "VA"), ("North Las Vegas", "NV"), ("Gilbert", "AZ"), ("Chandler", "AZ"),
    ("Scottsdale", "AZ"), ("Glendale", "AZ"), ("Mesa", "AZ"), ("Aurora", "CO"),
    ("Lakewood", "CO"), ("Colorado Springs", "CO"), ("Fort Collins", "CO"), ("Denver", "CO"),
    ("West Jordan", "UT"), ("Sandy", "UT"), ("Provo", "UT"), ("Ogden", "UT"),
    ("Orem", "UT"), ("St. George", "UT"), ("Layton", "UT"), ("Taylorsville", "UT"),
    ("West Valley City", "UT"), ("South Jordan", "UT"), ("Lehi", "UT"), ("Millcreek", "UT"),
    ("Clearfield", "UT"), ("Bountiful", "UT"), ("Logan", "UT"), ("Murray", "UT"),
    ("Rialto", "CA"), ("Antioch", "CA"), ("Temecula", "CA"), ("Murrieta", "CA"),
    ("Jurupa Valley", "CA"), ("Chico", "CA"), ("El Monte", "CA"), ("Daly City", "CA"),
    ("Berkeley", "CA"), ("Downey", "CA"), ("Costa Mesa", "CA"), ("Inglewood", "CA"),
    ("West Covina", "CA"), ("Norwalk", "CA"), ("Burbank", "CA"), ("El Cajon", "CA"),
    ("Santa Rosa", "CA"), ("Vallejo", "CA"), ("Victorville", "CA"), ("Fairfield", "CA"),
    ("Carlsbad", "CA"), ("Murrieta", "CA"), ("Temecula", "CA"), ("Clovis", "CA"),
    ("Westminster", "CA"), ("Simi Valley", "CA"), ("Thousand Oaks", "CA"), ("Ventura", "CA"),
    ("Santa Barbara", "CA"), ("San Buenaventura", "CA"), ("Oxnard", "CA"), ("Camarillo", "CA"),
    ("Palmdale", "CA"), ("Lancaster", "CA"), ("Pomona", "CA"), ("Ontario", "CA"),
    ("Rancho Cucamonga", "CA"), ("Fontana", "CA"), ("San Bernardino", "CA"), ("Rialto", "CA"),
    ("Colton", "CA"), ("Moreno Valley", "CA"), ("Riverside", "CA"), ("Corona", "CA"),
    ("Jurupa Valley", "CA"), ("Murrieta", "CA"), ("Menifee", "CA"), ("Temecula", "CA"),
    ("Hemet", "CA"), ("Perris", "CA"), ("Indio", "CA"), ("Palm Springs", "CA"),
    ("Palm Desert", "CA"), ("Cathedral City", "CA"), ("Coachella", "CA"),
    ("Tulare", "CA"), ("Hanford", "CA"), ("Visalia", "CA"), ("Fresno", "CA"),
    ("Clovis", "CA"), ("Madera", "CA"), ("Merced", "CA"), ("Modesto", "CA"),
    ("Stockton", "CA"), ("Turlock", "CA"), ("Tracy", "CA"), ("Manteca", "CA"),
    ("Lodi", "CA"), ("Elk Grove", "CA"), ("Roseville", "CA"), ("Folsom", "CA"),
    ("Vacaville", "CA"), ("Fairfield", "CA"), ("Vallejo", "CA"), ("Napa", "CA"),
    ("Santa Rosa", "CA"), ("Petaluma", "CA"), ("Rohnert Park", "CA"),
    ("South Bend", "IN"), ("Fort Wayne", "IN"), ("Evansville", "IN"), ("Gary", "IN"),
    ("Carmel", "IN"), ("Fishers", "IN"), ("Bloomington", "IN"), ("Hammond", "IN"),
    ("Lafayette", "IN"), ("Muncie", "IN"), ("Terre Haute", "IN"), ("Noblesville", "IN"),
    ("Columbus", "IN"), ("Anderson", "IN"), ("Greenwood", "IN"), ("Kokomo", "IN"),
    ("Cleveland", "OH"), ("Columbus", "OH"), ("Cincinnati", "OH"), ("Toledo", "OH"),
    ("Akron", "OH"), ("Dayton", "OH"), ("Parma", "OH"), ("Canton", "OH"),
    ("Lorain", "OH"), ("Hamilton", "OH"), ("Springfield", "OH"), ("Kettering", "OH"),
    ("Elyria", "OH"), ("Lakewood", "OH"), ("Youngstown", "OH"), ("Cuyahoga Falls", "OH"),
    ("Detroit", "MI"), ("Grand Rapids", "MI"), ("Warren", "MI"), ("Sterling Heights", "MI"),
    ("Ann Arbor", "MI"), ("Lansing", "MI"), ("Flint", "MI"), ("Dearborn", "MI"),
    ("Livonia", "MI"), ("Westland", "MI"), ("Troy", "MI"), ("Southfield", "MI"),
    ("Kalamazoo", "MI"), ("Wyoming", "MI"), ("Muskegon", "MI"), ("Pontiac", "MI"),
    ("Saginaw", "MI"), ("Kentwood", "MI"), ("East Lansing", "MI"),
    ("Minneapolis", "MN"), ("St. Paul", "MN"), ("Rochester", "MN"), ("Duluth", "MN"),
    ("Brooklyn Park", "MN"), ("Plymouth", "MN"), ("Maple Grove", "MN"), ("Coon Rapids", "MN"),
    ("Burnsville", "MN"), ("Blaine", "MN"), ("Lakeville", "MN"), ("Minnetonka", "MN"),
    ("Apple Valley", "MN"), ("Edina", "MN"), ("Eden Prairie", "MN"),
    ("Chicago", "IL"), ("Aurora", "IL"), ("Joliet", "IL"), ("Rockford", "IL"),
    ("Naperville", "IL"), ("Springfield", "IL"), ("Elgin", "IL"), ("Peoria", "IL"),
    ("Champaign", "IL"), ("Waukegan", "IL"), ("Cicero", "IL"), ("Bloomington", "IL"),
    ("Arlington Heights", "IL"), ("Evanston", "IL"), ("Decatur", "IL"),
    ("Houston", "TX"), ("San Antonio", "TX"), ("Dallas", "TX"), ("Austin", "TX"),
    ("Fort Worth", "TX"), ("El Paso", "TX"), ("Arlington", "TX"), ("Corpus Christi", "TX"),
    ("Plano", "TX"), ("Laredo", "TX"), ("Lubbock", "TX"), ("Garland", "TX"),
    ("Irving", "TX"), ("Amarillo", "TX"), ("Grand Prairie", "TX"), ("McKinney", "TX"),
    ("Frisco", "TX"), ("Pasadena", "TX"), ("Mesquite", "TX"), ("Killeen", "TX"),
    ("McAllen", "TX"), ("Carrollton", "TX"), ("Midland", "TX"), ("Waco", "TX"),
    ("Denton", "TX"), ("Abilene", "TX"), ("Beaumont", "TX"), ("Round Rock", "TX"),
    ("Odessa", "TX"), ("Richardson", "TX"), ("Pearland", "TX"), ("Lewisville", "TX"),
    ("Tyler", "TX"), ("College Station", "TX"), ("League City", "TX"), ("Wichita Falls", "TX"),
    ("Allen", "TX"), ("Murfreesboro", "TN"), ("Memphis", "TN"), ("Nashville", "TN"),
    ("Knoxville", "TN"), ("Chattanooga", "TN"), ("Clarksville", "TN"), ("Jackson", "TN"),
    ("Johnson City", "TN"), ("Kingsport", "TN"), ("Franklin", "TN"),
    ("Jacksonville", "FL"), ("Miami", "FL"), ("Tampa", "FL"), ("Orlando", "FL"),
    ("St. Petersburg", "FL"), ("Hialeah", "FL"), ("Tallahassee", "FL"), ("Fort Lauderdale", "FL"),
    ("Port St. Lucie", "FL"), ("Cape Coral", "FL"), ("Pembroke Pines", "FL"), ("Hollywood", "FL"),
    ("Miramar", "FL"), ("Gainesville", "FL"), ("Coral Springs", "FL"), ("Clearwater", "FL"),
    ("Palm Bay", "FL"), ("Pompano Beach", "FL"), ("West Palm Beach", "FL"), ("Lakeland", "FL"),
    ("Davie", "FL"), ("Miami Gardens", "FL"), ("Sunrise", "FL"), ("Boca Raton", "FL"),
    ("Deltona", "FL"), ("Plantation", "FL"), ("Sunrise", "FL"), ("Palm Coast", "FL"),
    ("Deerfield Beach", "FL"), ("Melbourne", "FL"), ("Boynton Beach", "FL"),
    ("Atlanta", "GA"), ("Columbus", "GA"), ("Augusta", "GA"), ("Savannah", "GA"),
    ("Athens", "GA"), ("Sandy Springs", "GA"), ("Roswell", "GA"), ("Macon", "GA"),
    ("Johns Creek", "GA"), ("Albany", "GA"), ("Warner Robins", "GA"), ("Alpharetta", "GA"),
    ("Marietta", "GA"), ("Valdosta", "GA"), ("Smyrna", "GA"),
    ("Charlotte", "NC"), ("Raleigh", "NC"), ("Greensboro", "NC"), ("Durham", "NC"),
    ("Winston-Salem", "NC"), ("Fayetteville", "NC"), ("Cary", "NC"), ("Wilmington", "NC"),
    ("High Point", "NC"), ("Concord", "NC"), ("Asheville", "NC"), ("Gastonia", "NC"),
    ("Greenville", "NC"), ("Jacksonville", "NC"), ("Chapel Hill", "NC"),
    ("Virginia Beach", "VA"), ("Norfolk", "VA"), ("Chesapeake", "VA"), ("Richmond", "VA"),
    ("Newport News", "VA"), ("Alexandria", "VA"), ("Hampton", "VA"), ("Roanoke", "VA"),
    ("Portsmouth", "VA"), ("Suffolk", "VA"), ("Lynchburg", "VA"), ("Harrisonburg", "VA"),
    ("Charlottesville", "VA"), ("Manassas", "VA"),
    ("Phoenix", "AZ"), ("Tucson", "AZ"), ("Mesa", "AZ"), ("Chandler", "AZ"),
    ("Glendale", "AZ"), ("Scottsdale", "AZ"), ("Gilbert", "AZ"), ("Tempe", "AZ"),
    ("Peoria", "AZ"), ("Surprise", "AZ"), ("Yuma", "AZ"), ("Avondale", "AZ"),
    ("Flagstaff", "AZ"), ("Goodyear", "AZ"), ("Casas Adobes", "AZ"), ("Buckeye", "AZ"),
    ("Lake Havasu City", "AZ"), ("Maricopa", "AZ"), ("Sierra Vista", "AZ"),
    ("Philadelphia", "PA"), ("Pittsburgh", "PA"), ("Allentown", "PA"), ("Erie", "PA"),
    ("Reading", "PA"), ("Scranton", "PA"), ("Bethlehem", "PA"), ("Lancaster", "PA"),
    ("Harrisburg", "PA"), ("Altoona", "PA"), ("York", "PA"), ("State College", "PA"),
    ("Wilkes-Barre", "PA"),
    ("New York", "NY"), ("Buffalo", "NY"), ("Rochester", "NY"), ("Yonkers", "NY"),
    ("Syracuse", "NY"), ("Albany", "NY"), ("New Rochelle", "NY"), ("Mount Vernon", "NY"),
    ("Schenectady", "NY"), ("Utica", "NY"), ("White Plains", "NY"), ("Troy", "NY"),
    ("Binghamton", "NY"),
    ("Seattle", "WA"), ("Spokane", "WA"), ("Tacoma", "WA"), ("Vancouver", "WA"),
    ("Bellevue", "WA"), ("Kirkland", "WA"), ("Kennewick", "WA"), ("Renton", "WA"),
    ("Bellingham", "WA"), ("Yakima", "WA"), ("Marysville", "WA"), ("Redmond", "WA"),
    ("Shoreline", "WA"), ("Richland", "WA"), ("Lakewood", "WA"),
    ("Portland", "OR"), ("Eugene", "OR"), ("Salem", "OR"), ("Gresham", "OR"),
    ("Hillsboro", "OR"), ("Beaverton", "OR"), ("Bend", "OR"), ("Medford", "OR"),
    ("Springfield", "OR"), ("Corvallis", "OR"), ("Albany", "OR"), ("Tigard", "OR"),
    ("Lake Oswego", "OR"), ("Keizer", "OR"),
    ("Denver", "CO"), ("Colorado Springs", "CO"), ("Aurora", "CO"), ("Fort Collins", "CO"),
    ("Lakewood", "CO"), ("Thornton", "CO"), ("Arvada", "CO"), ("Westminster", "CO"),
    ("Pueblo", "CO"), ("Centennial", "CO"), ("Boulder", "CO"), ("Highlands Ranch", "CO"),
    ("Greeley", "CO"), ("Longmont", "CO"), ("Loveland", "CO"), ("Broomfield", "CO"),
    ("Castle Rock", "CO"), ("Commerce City", "CO"), ("Parker", "CO"),
    ("Las Vegas", "NV"), ("Henderson", "NV"), ("Reno", "NV"), ("North Las Vegas", "NV"),
    ("Sparks", "NV"), ("Carson City", "NV"), ("Fernley", "NV"), ("Elko", "NV"),
    ("Mesquite", "NV"), ("Boulder City", "NV"),
    ("Albuquerque", "NM"), ("Las Cruces", "NM"), ("Rio Rancho", "NM"), ("Santa Fe", "NM"),
    ("Roswell", "NM"), ("Farmington", "NM"), ("Clovis", "NM"), ("Hobbs", "NM"),
    ("Alamogordo", "NM"), ("Carlsbad", "NM"),
    ("Salt Lake City", "UT"), ("West Valley City", "UT"), ("Provo", "UT"), ("West Jordan", "UT"),
    ("Orem", "UT"), ("Sandy", "UT"), ("St. George", "UT"), ("Ogden", "UT"),
    ("Layton", "UT"), ("South Jordan", "UT"), ("Lehi", "UT"), ("Millcreek", "UT"),
    ("Kansas City", "MO"), ("St. Louis", "MO"), ("Springfield", "MO"), ("Columbia", "MO"),
    ("Independence", "MO"), ("Lee's Summit", "MO"), ("O'Fallon", "MO"), ("St. Joseph", "MO"),
    ("St. Charles", "MO"), ("Blue Springs", "MO"), ("Joplin", "MO"), ("Florissant", "MO"),
    ("Omaha", "NE"), ("Lincoln", "NE"), ("Bellevue", "NE"), ("Grand Island", "NE"),
    ("Kearney", "NE"), ("Fremont", "NE"), ("Hastings", "NE"), ("Norfolk", "NE"),
    ("Des Moines", "IA"), ("Cedar Rapids", "IA"), ("Davenport", "IA"), ("Sioux City", "IA"),
    ("Iowa City", "IA"), ("Waterloo", "IA"), ("Council Bluffs", "IA"), ("Ames", "IA"),
    ("West Des Moines", "IA"), ("Dubuque", "IA"), ("Ankeny", "IA"),
    ("Wichita", "KS"), ("Overland Park", "KS"), ("Kansas City", "KS"), ("Olathe", "KS"),
    ("Topeka", "KS"), ("Lawrence", "KS"), ("Shawnee", "KS"), ("Manhattan", "KS"),
    ("Lenexa", "KS"), ("Salina", "KS"),
    ("Oklahoma City", "OK"), ("Tulsa", "OK"), ("Norman", "OK"), ("Broken Arrow", "OK"),
    ("Lawton", "OK"), ("Edmond", "OK"), ("Moore", "OK"), ("Midwest City", "OK"),
    ("Stillwater", "OK"), ("Enid", "OK"),
    ("Fayetteville", "AR"), ("Little Rock", "AR"), ("Fort Smith", "AR"), ("Springdale", "AR"),
    ("Jonesboro", "AR"), ("North Little Rock", "AR"), ("Conway", "AR"), ("Rogers", "AR"),
    ("Pine Bluff", "AR"), ("Bentonville", "AR"),
    ("New Orleans", "LA"), ("Baton Rouge", "LA"), ("Shreveport", "LA"), ("Lafayette", "LA"),
    ("Lake Charles", "LA"), ("Kenner", "LA"), ("Bossier City", "LA"), ("Monroe", "LA"),
    ("Alexandria", "LA"), ("Houma", "LA"),
    ("Jackson", "MS"), ("Gulfport", "MS"), ("Southaven", "MS"), ("Hattiesburg", "MS"),
    ("Biloxi", "MS"), ("Meridian", "MS"), ("Tupelo", "MS"), ("Olive Branch", "MS"),
    ("Greenville", "MS"), ("Horn Lake", "MS"),
    ("Birmingham", "AL"), ("Montgomery", "AL"), ("Huntsville", "AL"), ("Mobile", "AL"),
    ("Tuscaloosa", "AL"), ("Hoover", "AL"), ("Dothan", "AL"), ("Auburn", "AL"),
    ("Decatur", "AL"), ("Madison", "AL"), ("Florence", "AL"), ("Phenix City", "AL"),
    ("Nashville", "TN"), ("Memphis", "TN"), ("Knoxville", "TN"), ("Chattanooga", "TN"),
    ("Clarksville", "TN"), ("Murfreesboro", "TN"), ("Franklin", "TN"), ("Jackson", "TN"),
    ("Johnson City", "TN"), ("Bartlett", "TN"), ("Hendersonville", "TN"), ("Kingsport", "TN"),
    ("Louisville", "KY"), ("Lexington", "KY"), ("Bowling Green", "KY"), ("Owensboro", "KY"),
    ("Covington", "KY"), ("Hopkinsville", "KY"), ("Frankfort", "KY"), ("Henderson", "KY"),
    ("Cincinnati", "OH"), ("Cleveland", "OH"), ("Columbus", "OH"), ("Toledo", "OH"),
    ("Akron", "OH"), ("Dayton", "OH"), ("Parma", "OH"), ("Canton", "OH"),
    ("Charleston", "WV"), ("Huntington", "WV"), ("Parkersburg", "WV"), ("Morgantown", "WV"),
    ("Wheeling", "WV"), ("Weirton", "WV"),
    ("Baltimore", "MD"), ("Frederick", "MD"), ("Rockville", "MD"), ("Gaithersburg", "MD"),
    ("Bowie", "MD"), ("Hagerstown", "MD"), ("Annapolis", "MD"), ("College Park", "MD"),
    ("Salisbury", "MD"), ("Laurel", "MD"),
    ("Washington", "DC"),
    ("Boston", "MA"), ("Worcester", "MA"), ("Springfield", "MA"), ("Lowell", "MA"),
    ("Cambridge", "MA"), ("New Bedford", "MA"), ("Brockton", "MA"), ("Quincy", "MA"),
    ("Lynn", "MA"), ("Fall River", "MA"), ("Newton", "MA"), ("Lawrence", "MA"),
    ("Providence", "RI"), ("Cranston", "RI"), ("Warwick", "RI"), ("Pawtucket", "RI"),
    ("East Providence", "RI"), ("Woonsocket", "RI"), ("Coventry", "RI"),
    ("Bridgeport", "CT"), ("New Haven", "CT"), ("Stamford", "CT"), ("Hartford", "CT"),
    ("Waterbury", "CT"), ("Norwalk", "CT"), ("Danbury", "CT"), ("New Britain", "CT"),
    ("Bristol", "CT"), ("Meriden", "CT"),
    ("Newark", "NJ"), ("Jersey City", "NJ"), ("Paterson", "NJ"), ("Elizabeth", "NJ"),
    ("Edison", "NJ"), ("Woodbridge", "NJ"), ("Lakewood", "NJ"), ("Toms River", "NJ"),
    ("Hamilton", "NJ"), ("Trenton", "NJ"), ("Clifton", "NJ"), ("Camden", "NJ"),
    ("Cherry Hill", "NJ"), ("Passaic", "NJ"), ("Union City", "NJ"),
    ("Portland", "ME"), ("Lewiston", "ME"), ("Bangor", "ME"), ("South Portland", "ME"),
    ("Auburn", "ME"), ("Biddeford", "ME"),
    ("Manchester", "NH"), ("Nashua", "NH"), ("Concord", "NH"), ("Dover", "NH"),
    ("Rochester", "NH"), ("Keene", "NH"), ("Derry", "NH"),
    ("Burlington", "VT"), ("South Burlington", "VT"), ("Rutland", "VT"), ("Essex", "VT"),
    ("Milwaukee", "WI"), ("Madison", "WI"), ("Green Bay", "WI"), ("Kenosha", "WI"),
    ("Racine", "WI"), ("Appleton", "WI"), ("Waukesha", "WI"), ("Eau Claire", "WI"),
    ("Oshkosh", "WI"), ("Janesville", "WI"), ("West Allis", "WI"), ("La Crosse", "WI"),
    ("Sioux Falls", "SD"), ("Rapid City", "SD"), ("Aberdeen", "SD"), ("Brookings", "SD"),
    ("Watertown", "SD"), ("Mitchell", "SD"),
    ("Fargo", "ND"), ("Bismarck", "ND"), ("Grand Forks", "ND"), ("Minot", "ND"),
    ("West Fargo", "ND"), ("Mandan", "ND"),
    ("Billings", "MT"), ("Missoula", "MT"), ("Great Falls", "MT"), ("Bozeman", "MT"),
    ("Butte", "MT"), ("Helena", "MT"), ("Kalispell", "MT"),
    ("Boise", "ID"), ("Nampa", "ID"), ("Meridian", "ID"), ("Idaho Falls", "ID"),
    ("Pocatello", "ID"), ("Caldwell", "ID"), ("Coeur d'Alene", "ID"), ("Twin Falls", "ID"),
    ("Cheyenne", "WY"), ("Casper", "WY"), ("Laramie", "WY"), ("Gillette", "WY"),
    ("Rock Springs", "WY"), ("Sheridan", "WY"),
    ("Anchorage", "AK"), ("Fairbanks", "AK"), ("Juneau", "AK"), ("Sitka", "AK"),
    ("Ketchikan", "AK"),
    ("Honolulu", "HI"), ("Pearl City", "HI"), ("Hilo", "HI"), ("Kailua", "HI"),
    ("Waipahu", "HI"), ("Kaneohe", "HI"), ("Mililani", "HI"), ("Kahului", "HI"),
    ("Greenville", "SC"), ("Columbia", "SC"), ("North Charleston", "SC"), ("Mount Pleasant", "SC"),
    ("Rock Hill", "SC"), ("Summerville", "SC"), ("Goose Creek", "SC"), ("Hilton Head", "SC"),
    ("Florence", "SC"), ("Spartanburg", "SC"), ("Sumter", "SC"), ("Myrtle Beach", "SC"),
]

# Deduplicate while preserving order
seen = set()
_deduped = []
for c in US_CITIES:
    k = f"{c[0]},{c[1]}"
    if k not in seen:
        seen.add(k)
        _deduped.append(c)
US_CITIES = _deduped


def get_cities(mode: str, custom: str = "") -> list:
    """Return list of 'City, ST' strings for the given mode."""
    if mode == "Custom":
        return [custom] if custom else ["Las Vegas, NV"]
    n = {"Top 10": 10, "Top 100": 100, "Top 1000": 1000}.get(mode, len(US_CITIES))
    subset = US_CITIES[:n]
    return [f"{city}, {state}" for city, state in subset]


CITY_COUNTS = {
    "Custom":   None,
    "Top 10":   10,
    "Top 100":  100,
    "Top 1000": 1000,
    "All US":   None,  # set at runtime
}
